---
volumes:
  postgres_data:
  redis_data:
    driver: local
networks:
  backend: {}
services:
  db:
    image: postgres:17.4-bookworm
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    # profiles:
    #   - "postgres"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '15432:5432'
    networks:
      backend:
        aliases:
          - postgres
  redis:
    image: redis:7.4-bookworm
    # profiles:
    #   - "redis"
    ports:
      - '6379:6379'
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
    volumes:
      - redis_data:/data
    networks:
      - backend
  web:
    build: .
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    networks:
      backend:
        aliases:
          - frontend
    volumes:
      - .:/rails
      - ./homedir/inputrc:/home/rails/.inputrc:delegated
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
